version: 1
disable_existing_loggers: true

formatters:
    console:
        (): src.loggers.ProjectPathFormatter
        format: "[%(asctime)s][%(levelname)-5.5s][%(projectpath)s:%(lineno)d] %(message)s"
        datefmt: "%H:%M:%S"
    file:
        (): src.loggers.ProjectPathFormatter
        format: "[%(asctime)s][%(levelname)-5.5s][%(projectpath)s:%(lineno)d] %(message)s"
        datefmt: "%H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: console

    file:
        class: src.loggers.DatedFileHandler
        level: DEBUG
        formatter: file
        filename: artifacts/%Y%m%d%H%M%S_tests_run.log
        mode: w

root:
    level: NOTSET
    handlers: [console, file]
    propagate: yes
